import { Inter } from "next/font/google";
import "./globals.css";
import StackedLightHeaderAndFooter from "./components/Navbar";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}flex flex-col h-screen  dark:bg-gray-900 text-white max-w-[1280px] mx-auto `}
      >
        <SpeedInsights />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
